version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  build-worklow:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            package.json run-build-test-ts true
          config-path: ./circleci/continue_config.yml
          base-revision: << pipeline.git.base_revision >>