version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

jobs:
  print-things:
    docker:
      - image: cimg/base:2024.05
    steps:
      - run:
          name: Print things
          command: |
            echo "pipeline.git."
            echo "The current run name is $CIRCLE_JOB"

workflows:
  configure-worklow:
    jobs:
      - path-filtering/filter:
          name: check-and-schedule-build-test-workflow
          mapping: |
            package.json|yarn.lock|packages/.* run-build-test-ts true
            scala/.* run-build-test-scala true
            santa_barbara_restore/.* run-build-test-santa_barbara-restore true
            .circleci/.* run-circleci-config true
          config-path: .circleci/continue_config.yml
          base-revision: develop
          filters:
            branches:
              ignore:
                - develop
                - release
      - path-filtering/filter:
          name: schedule-deploy-workflow
          mapping: |
            .* run-deploy true
          config-path: .circleci/continue_config.yml
          base-revision: develop
          filters:
            branches:
              only:
                - develop
                - release
