version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the path-filtering orb is required to continue a pipeline based on
# the path of an updated fileset
orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  workflow-setup:
    jobs:
      - path-filtering/filter:
          name: set-changed-project-parameters
          mapping: |
            package.json|yarn.lock|packages/* run-build-ts-job true
            scarre/.* run-build-scarre-job true
            yardi-restore/.* run-build-yardi-restore-job true
          base-revision: main
          config-path: .circleci/continue_config.yml
          filters:
            branches:
              ignore:
                - main
      - path-filtering/filter:
            name: set-all-jobs-true
            mapping: |
              .* all-jobs true
            base-revision: main
            config-path: .circleci/continue_config.yml
            filters:
              branches:
                only:
                  - main