version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

jobs:
  setup:
    executor: path-filter/default
    steps:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            package.json|yarn.lock|packages/**/* run-build-test-ts true
            scarre/**/* run-build-test-scarre true
            yardi-restore/**/* run-build-test-yardi-restore true
          config-path: ./circleci/continue_config.yml