version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  configure-worklow:
    jobs:
      - path-filtering/filter:
          name: check-changed-files
          mapping: |
            package.json|yarn.lock|packages/*/* run-build-test-ts true
            scala/*/* run-build-test-scala true
            santa_barbara_restore/*/* run-build-test-santa_barbara-restore true
            .circleci/* run-circleci-config true
          config-path: .circleci/continue_config.yml
          base-revision: << pipeline.git.base_revision >>
