version: 2.1

parameters:
  run-build-ts-job:
    type: boolean
    default: false
  run-build-scarre-job:
    type: boolean
    default: false
  all-jobs:
    type: boolean
    default: false

jobs:
  run-build-service-1-job:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Building service 1"

  run-build-service-2-job:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Building service 2"

  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Deploying"

workflows:
  build-and-test-ts:
    when: << pipeline.parameters.run-build-ts-job >>
    jobs:
      - run-build-service-1-job
  build-and-test-scarre:
    when: << pipeline.parameters.run-build-scarre-job >>
    jobs:
      - run-build-service-2-job
  deploy:
    when: << pipeline.parameters.all-jobs >>
    jobs:
      - deploy
    depends_on:
      - build-and-test-ts
      - build-and-test-scarre